
CREATE DATABASE IF NOT EXISTS CRUD
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE CRUD;


DROP TABLE IF EXISTS Personas;
CREATE TABLE IF NOT EXISTS Personas (
  id int(11) NOT NULL AUTO_INCREMENT,
  Nombre varchar(45) DEFAULT NULL,
  Apellido varchar(45) DEFAULT NULL,
  Email varchar(45) DEFAULT NULL,
  Telefono varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;